/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class isl_model_ref_AbstractCDModelTest */

#ifndef _Included_isl_model_ref_AbstractCDModelTest
#define _Included_isl_model_ref_AbstractCDModelTest
#ifdef __cplusplus
extern "C" {
#endif
#undef isl_model_ref_AbstractCDModelTest_ECD_ULPS
#define isl_model_ref_AbstractCDModelTest_ECD_ULPS 5L
#undef isl_model_ref_AbstractCDModelTest_BESSEL_ULPS
#define isl_model_ref_AbstractCDModelTest_BESSEL_ULPS 1000000L
#undef isl_model_ref_AbstractCDModelTest_INTEGRAND_ULPS
#define isl_model_ref_AbstractCDModelTest_INTEGRAND_ULPS 5L
#undef isl_model_ref_AbstractCDModelTest_COMPLEX_MATH_ULPS
#define isl_model_ref_AbstractCDModelTest_COMPLEX_MATH_ULPS 5L
#undef isl_model_ref_AbstractCDModelTest_LAPLACE_ECD_ULPS
#define isl_model_ref_AbstractCDModelTest_LAPLACE_ECD_ULPS 5L
#undef isl_model_ref_AbstractCDModelTest_G_ULPS
#define isl_model_ref_AbstractCDModelTest_G_ULPS 5L
/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    setCppLogLevel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_isl_model_ref_AbstractCDModelTest_setCppLogLevel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    createCppCDM
 * Signature: (Lisl/model/ref/AbstractCDModel;)J
 */
JNIEXPORT jlong JNICALL Java_isl_model_ref_AbstractCDModelTest_createCppCDM
  (JNIEnv *, jobject, jobject);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    deleteCppCDM
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_isl_model_ref_AbstractCDModelTest_deleteCppCDM
  (JNIEnv *, jobject, jlong);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    ecd
 * Signature: (JDD)D
 */
JNIEXPORT jdouble JNICALL Java_isl_model_ref_AbstractCDModelTest_ecd
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    integrand
 * Signature: (JDDD)D
 */
JNIEXPORT jdouble JNICALL Java_isl_model_ref_AbstractCDModelTest_integrand
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    bessel
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_isl_model_ref_AbstractCDModelTest_bessel
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    complexMath
 * Signature: (Ljava/lang/String;Lisl/util/Complex;)Lisl/util/Complex;
 */
JNIEXPORT jobject JNICALL Java_isl_model_ref_AbstractCDModelTest_complexMath
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    l_ecd
 * Signature: (JLisl/util/Complex;)Lisl/util/Complex;
 */
JNIEXPORT jobject JNICALL Java_isl_model_ref_AbstractCDModelTest_l_1ecd
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     isl_model_ref_AbstractCDModelTest
 * Method:    g
 * Signature: (JLisl/util/Complex;)Lisl/util/Complex;
 */
JNIEXPORT jobject JNICALL Java_isl_model_ref_AbstractCDModelTest_g
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
